spring.application.name=redmine-task-exporter
server.port=8080

# ===================================================================
# DataSource
# ===================================================================
spring.datasource.url=jdbc:postgresql://10.1.51.31:5450/pje_1g?options=-c%20client_encoding=UTF8
spring.datasource.username=${USER_LDAP:postgres}
spring.datasource.password=${PASSWORD_LDAP:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===================================================================
# JPA Properties
# ===================================================================
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
